### ISSUE TITLE
Agent Observation

### ISSUE THREAD

**Issue by DongChen06** [cjdjr/T-MAAC#1]
Dear authors, thanks for the wonderful paper and codes. I have a question about the agents' observations. In the paper, you mentioned that agents in the same zone will share the same observation but add their agent_id as the identification. Does that mean agents in the same zone will make similar actions if we do not take account of randomness in the action sampling process? If so, how to make sure agents in the same zone make suitable actions but with the same observations?

Thanks so much!

**Comment by cjdjr** [comment]
Thank you for your interest in our work! 
In fact, as you said, agents in the same zone will make similar actions due to the same observation. However, in our work, we take the index of node installed with the agent as a prior knowledge (see the last paragraph of Section 3.2), which makes the agent aware of its own location in the zone. And then, agents in the same zone will obtain different representations through our Embedding Aggregation module.

**Comment by DongChen06** [comment]
Hi authors, I still have a question about the observation space. According to the paper, the obs can include the p_i to indicate the position (node id) of the agent.
![image](https://user-images.githubusercontent.com/25771207/216772242-13df19f3-0537-4754-831d-dfe6f26cc8c2.png)

However, when I look at the code: https://github.com/cjdjr/T-MAAC/blob/1b875a181ac309f72ab637883a03809f81c24514/models/model.py#L118-L125 The agent id is just a diagonal matrix that is not the id of the node in which the agent is installed. Could you please help me understand it? Thank you!

**Comment by cjdjr** [comment]
> 

We implement T-MADDPG in the class ICSTRANSMADDPG which overrides some functions in model.py.
https://github.com/cjdjr/T-MAAC/blob/1b875a181ac309f72ab637883a03809f81c24514/models/ics_trans_maddpg.py#L12
